<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <Import Project="../KernelSources.props" />
  <ItemGroup>
    <ProjectReference Include="../PluginApi/TraceSoul2.PluginApi.csproj" />
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.19.2" />
    <Compile Include="Program.cs" />
  </ItemGroup>
</Project>
